@Library("jenkins_library") _

def build = new org.devops.build()

pipeline {
    agent any

    parameters {
        choice(
            name: 'HG_REPOSITORY_SRC',
            choices: [
                'https://svn100.hotgamehl.com/svn/Html5/trunk/dldl_WX/mengdao2_trunk_rc',
                'https://svn100.hotgamehl.com/svn/Html5/trunk/dldl_WX/mengdao2_trunk'
            ],
            description: '项目地址'
        )
        string(
            name: 'HG_MINIGAME_REPOSITORY_SRC',
            defaultValue: 'https://svn100.hotgamehl.com/svn/Html5/trunk/dldl_WX/moli_wx_main',
            description: '小游戏地址'
        )
        string(name: 'MINIGAME_TAG', defaultValue: 'mengdao2_wxgame', description: '目录名')
        booleanParam(name: 'ENABLE_PUBLISH_STATIC_RESOURCE', defaultValue: true, description: '是否发布静态资源')

        string(name: 'upload_filter', defaultValue: 'default')
        string(name: 'toolTag', defaultValue: 'moli_cfg_tx_cdn')
        string(name: 'cfg_dir', defaultValue: 'md2')
        string(name: 'target', defaultValue: 'wx_main')
        string(name: 'cfgTag', defaultValue: 'wx')

        string(name: 'APP_ID', defaultValue: 'wx561e6eb0ca55e538')
        string(name: 'PRIVATE_KEY', defaultValue: './key/private.wx561e6eb0ca55e538.key')

        booleanParam(name: 'addResVer', defaultValue: false, description: '提升资源版本号')
        booleanParam(name: 'addCodeVer', defaultValue: false, description: '提升代码版本号')
    }

    options {
        disableConcurrentBuilds()
    }

    stages {
        stage('初始化') {
            steps {
                script {
                    build.cleanupHGPubToolsDist()

                    dir("project") {
                        build.checkoutSVN(params.HG_REPOSITORY_SRC)
                    }

                    build.checkoutPublish()

                    dir(params.MINIGAME_TAG) {
                        build.checkoutSVN(params.HG_MINIGAME_REPOSITORY_SRC)
                    }

                    // Send Notify
                    build.sendStart2DingTalk_PubMinigame()
                }
            }
        }
        stage('代码发布') {
            steps {
                script {
                    lock(resource: "pub2web") {
                        dir('publish') {
                            bat "npx hgbuild run _12_common_xyx --prg_dir ${WORKSPACE}/project --cfg_dir ${params.cfg_dir} --target ${params.target} --target_dir ${WORKSPACE}/${params.MINIGAME_TAG} --appid ${params.APP_ID} --key ${params.PRIVATE_KEY}" + (params.addResVer ? ' --addResVer' : '') + (params.addCodeVer ? ' --addCodeVer' : '')
                        }
                    }
                }
            }
            options {
                timeout(3)
            }
        }
        stage('资源发布') {
            steps {
                script {
                    lock(resource: "pub2web") {
                        dir('publish') {
                            bat "npx hgbuild run _12_common_xyx_res --upload_filter ${params.upload_filter} --toolTag ${params.toolTag} --cfg_dir ${params.cfg_dir} --target ${params.target} --cfgTag ${params.cfgTag} --noUserOp" + (params.addResVer ? ' --addResVer' : '') + (params.addCodeVer ? ' --addCodeVer' : '')
                        }
                    }
                }
            }
            when { expression { params.ENABLE_PUBLISH_STATIC_RESOURCE } }
        }
    }

    post {
        always {
            script {
                build.sendResult2DingTalk_PubMinigame()
                build.sendResult2Emailext()
            }
        }
    }
}
