@Library("jenkins_library") _

def build = new org.devops.build()

// def zipUrlName = "";
// if (params.PROJECT_NAME == "seirei") {
//     zipUrlName = "${params.PROJECT_NAME}-精灵";
//     if (params.DST_LOCALE == "jp") {
//         zipUrlName += "中翻日"
//     }
//     if (params.DST_LOCALE == "en") {
//         zipUrlName += "日翻英"
//     }
// }
// def zipUrl = "https://i18n-api.g123.jp/jsonfile/zip/${zipUrlName}-ob${PROJECT_VER}-${ZIP_DATE}.zip"
// env.ZIP_URL = zipUrl
// println(zipUrl)

pipeline {
    agent any
    options {
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    // triggers {
    //     URLTrigger(
    //         // 计划任务
    //         cronTabSpec: 'H/2 * * * *',
    //         entries: [
    //             // URLTrigger
    //             URLTriggerEntry( 
    //                 url: "${ZIP_URL}", // 要检查的URL
    //                 checkLastModificationDate: true, // 检查修改时间
    //                 timeout: 300, // 超时(秒)
    //                 // username: 'myuser',
    //                 // password: 'mypassword',
    //                 checkETag: true,
    //                 // checkStatus: true,
    //                 // statusCode: 403,
    //                 // contentTypes: [
    //                 //     MD5Sum()
    //                 // ],
    //             ),
    //         ]
    //     )
    //     cron '0 0 * * *'
    // }
    stages {
        stage('retrieve_translation') {
            steps {
                script {
                    // httpRequest responseHandle: 'NONE', url: "${ZIP_URL}", wrapAsMultipart: false
                    build.retrieveTranslationAPI()
                }
            }
        }
    }
}