@Library("jenkins_library") _

def build = new org.devops.build()

pipeline {
    agent any
    options {
        disableConcurrentBuilds()
    }
    // triggers {
    //     URLTrigger(
    //         // 计划任务
    //         cronTabSpec: '*/2 * * * *',
    //         entries: [
    //             // URLTrigger
    //             URLTriggerEntry( 
    //                 url: "${TRIGGER_URL}", // 要检查的URL
    //                 // checkLastModificationDate: true, // 检查修改时间
    //                 timeout: 300, // 超时(秒)
    //                 requestHeaders: [
    //                     RequestHeader( headerName: "Authorization" , headerValue: "FLuCiEkQlqDdRtDQYHt856vWOO6+X0aG9MqAxyuYZe0" ),
    //                     RequestHeader( headerName: "Range" , headerValue: "bytes=0-31" ),
    //                 ],
    //                 contentTypes: [
    //                     MD5Sum()
    //                 ],
    //             ),
    //         ]
    //     )
    // }
    stages {
        stage('retrieve_translation') {
            steps {
                script {
                    // httpRequest responseHandle: 'NONE', url: "${ZIP_URL}", wrapAsMultipart: false
                    build.retrieveTranslationAPI()
                }
            }
        }
    }
    
    post { 
        failure { 
            script {
                build.sendCommonResult2DingTalk()
            }
        }
    }
}