@Library("jenkins_library") _

def build = new org.devops.build()

pipeline {
    agent any

    stages {
        stage('clean') {
            steps {
                print "clean"
                // deleteDir()
            }
        }
        stage('install hgbuild') {
            steps {
                script {
                    if (params.UPDATE_HGBUILDLIB) {
                        bat 'npm config set "@hotgame:registry" http://192.168.1.205:7000/'
                        bat 'npm install -g @hotgame/hgbuildlib'
                        bat 'hgtsc --version'        
                    }
                }
            }
        }
        stage('checkout') {
            steps {
                script {
                    if (!env.HG_PROTOBUF_PATH) {
                        env.HG_PROTOBUF_PATH = "src/protobuf/proto"
                    }
                    if (!env.HG_EXTRA_CREDENTIALS_ID) {
                        env.HG_EXTRA_CREDENTIALS_ID = '81e61ad7-0457-456c-b158-84db028669b9'
                    }
                    dir("project/${env.HG_PROTOBUF_PATH}") {
                        build.checkoutSVN("${params.HG_REPOSITORY_SRC}/${env.HG_PROTOBUF_PATH}", false, false)
                    }
                    dir("protobuf") {
                        checkout([$class: 'SubversionSCM', additionalCredentials: [], excludedCommitMessages: '', excludedRegions: '', excludedRevprop: '', excludedUsers: '', filterChangelog: false, ignoreDirPropChanges: false, includedRegions: '', locations: [[cancelProcessOnExternalsFail: true, credentialsId: env.HG_EXTRA_CREDENTIALS_ID, depthOption: 'infinity', ignoreExternalsOption: true, local: '.', remote: params.HG_REPOSITORY_SRC_PROTOBUF]], quietOperation: true, workspaceUpdater: [$class: 'UpdateUpdater']])
                    }
                }
            }
        }
        stage('sync protobuf file') {
            steps {
                fileOperations([fileCopyOperation(excludes: '', flattenFiles: true, includes: 'protobuf/*.proto', renameFiles: false, sourceCaptureExpression: '', targetLocation: "project/${env.HG_PROTOBUF_PATH}", targetNameExpression: '')])
                dir("project/${env.HG_PROTOBUF_PATH}") {
                    bat 'svn add . --no-ignore --force'
                    bat 'svn commit . -m "[0] Update protobuf file automatically"'
                }
            }
        }
        // stage('sync protobuf code') {
        //     steps {
        //         dir("project") {
        //             bat 'hgpbts'
                    
        //             bat 'svn commit -m "[0] Update protobuf code and config automatically" src/protobuf/protobufMsg.d.ts resource/protobufMsg.json src/protobuf/IProtobuf.ts'
        //         }
        //     }
        // }
    }
    
    post { 
        changed { 
            script {
                build.sendCommonResult2DingTalk()
            }
        }
    }
}
