@Library("jenkins_library") _

def build = new org.devops.build()

pipeline {
    agent any
    options {
        disableConcurrentBuilds()
    }

    stages {
        stage('build') {
            steps {
                script {
                    build.cleanupHGPubToolsDist()
                    dir("project") {
                        build.checkoutSVN(params.HG_REPOSITORY_SRC)
                        // 发送通知
                        build.sendStart2DingTalk_PubWeb()
                    }
                    build.checkoutAutomator()
                    lock(resource: "pub2web") {
                        env.pub_ver = bat returnStdout: true, script: '@echo off && %WORKSPACE%/automator/automator %WORKSPACE%/automator/cfg/dldl/pubver_upgrade.yml --FULL_AUTOMATIC 1 --LOG_LEVEL 99'
                        print env.pub_ver
                    }
                    bat '%WORKSPACE%/automator/automator %WORKSPACE%/automator/cfg/dldl/pub2cdn_complex.with_pubver.yml --FULL_AUTOMATIC 1 --workspaceFolder %WORKSPACE%/project'
                }
            }
        }
    }


    post { 
        always { 
            script {
                build.sendResult2DingTalk_PubWeb()
                build.sendResult2Emailext()
            }
        }
    }
}
