@Library("jenkins_library") _

def buildLib = new org.devops.build()

import groovy.json.JsonSlurperClassic

pipeline {
    agent any
    options {
        disableConcurrentBuilds()
    }

    stages {
        stage('checkout') {
            steps {
                script {
                    buildLib.checkoutAutomator()
                    dir("project/${CFGJSON_FOLDER}") {
                        buildLib.checkoutSVN("$HG_REPOSITORY_SRC/${CFGJSON_FOLDER}", false, false)
                    }
                    def localization_folder = LOCALIZATION_JSON.substring(0, LOCALIZATION_JSON.lastIndexOf("/"))
                    dir("project/$localization_folder") {
                        buildLib.checkoutSVN("$HG_REPOSITORY_SRC/$localization_folder", false, false)
                        def localization_str = readFile encoding: 'utf-8', file: "$WORKSPACE/project/$LOCALIZATION_JSON"
                        def localization_obj = new JsonSlurperClassic().parseText(localization_str)
                        env.APPID = localization_obj.appId
                    }
                    dir('translation') {
                        buildLib.checkoutSVN(HG_TRANSLATIONS_REPOSITORY_SRC, false, false)
                    }
                    env.WORKSPACE_FOLDER = "${WORKSPACE}/project"
                    env.TRANSLATION_FOLDER = "${WORKSPACE}/translation"
                    // 获取凭证
                    withCredentials([usernamePassword(credentialsId: buildLib.getCredentialsId(), passwordVariable: 'HG_CREDENTIAL_PASSWORD', usernameVariable: 'HG_CREDENTIAL_USERNAME')]) {
                        env.SVN_CREDENTIAL = "--username ${HG_CREDENTIAL_USERNAME} --password ${HG_CREDENTIAL_PASSWORD}"
                    }
                    
                }
            }
        }
        
        stage('build') {
            steps {
                script {
                    lock(resource: 'translation') {
                        dir('conversion') {
                            bat '%WORKSPACE%/automator/automator %WORKSPACE%/automator/cfg/translation_split/downloads.yml --FULL_AUTOMATIC 1'
                            bat '%WORKSPACE%/automator/automator %WORKSPACE%/automator/cfg/translation_split/apply.yml --FULL_AUTOMATIC 1 --isUpdate 1'
                        }
                    }
                    // 自动构建发布任务
                    if (params.BUILD_NEXT_JOB && params.NEXT_JOB) {
                        build wait: false, job: params.NEXT_JOB, parameters: [extendedChoice(name: 'HG_REPOSITORY_SRC', value: params.HG_REPOSITORY_SRC)]
                    }
                }
            }
        }
    }

    post { 
        changed { 
            script {
                buildLib.sendCommonResult2DingTalk()
            }
        }
    }
}
