/* groovylint-disable CompileStatic, NestedBlockDepth, NoDef, UnnecessaryGString, VariableName, VariableTypeRequired */
@Library("jenkins_library") _

def build = new org.devops.build()

pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    options {
        disableConcurrentBuilds()
        preserveStashes()
    }
    stages {
        stage('build') {
            steps {
                script {
                    build.pub200AutomaticIntegrated()
                }
            }
        }
    }

    post {
        always {
            script {
                print 'Done'
                if (build.needCompile()) {
                    build.sendResult2DingTalk()
                    if (params.MAIL_TO) {
                        build.sendResult2Emailext()
                    }
                }
            }
        }
    }
}
