@Library("jenkins_library") _

def build = new org.devops.build()

import groovy.json.JsonSlurperClassic



pipeline {
    agent any
    triggers {
        pollSCM 'H/2 * * * *'
    }
    options {
        disableConcurrentBuilds()
    }

    stages {
        stage('checkout') {
            steps {
                script {
                    build.checkoutAutomator()
                    def localization_folder = LOCALIZATION_JSON.substring(0, LOCALIZATION_JSON.lastIndexOf("/"))
                    dir("project/$localization_folder") {
                        build.checkoutSVN("$HG_REPOSITORY_SRC/$localization_folder", false, false)
                    }
                    dir('translation') {
                        def localization_str = readFile encoding: 'utf-8', file: "$WORKSPACE/project/$LOCALIZATION_JSON"
                        def localization_obj = new JsonSlurperClassic().parseText(localization_str)
                        def includedRegions = ".*/${localization_obj.appId}/${localization_obj.from_language}/.*"
                        print(includedRegions)
                        build.checkoutSVN(HG_TRANSLATIONS_REPOSITORY_SRC, true, true, true, ".", includedRegions)
                        env.APPID = localization_obj.appId
                    }
                    env.WORKSPACE_FOLDER = "${WORKSPACE}/project"
                    env.TRANSLATION_FOLDER = "${WORKSPACE}/translation"
                    // 手动操作
                    if (build.isManualTrigger()) {
                        // 0 表示完整推送
                        if (env.TRANSLATION_REVISIIONS == "0") {
                            env.TRANSLATION_SYNC_ALL = true
                        }
                    } else {
                        // 自动则使用增量版本
                        env.TRANSLATION_REVISIIONS = build.getRevisions()
                    }
                    // 获取凭证
                    withCredentials([usernamePassword(credentialsId: build.getCredentialsId(), passwordVariable: 'HG_CREDENTIAL_PASSWORD', usernameVariable: 'HG_CREDENTIAL_USERNAME')]) {
                        env.SVN_CREDENTIAL = "--username ${HG_CREDENTIAL_USERNAME} --password ${HG_CREDENTIAL_PASSWORD}"
                    }
                    
                }
            }
        }
        
        stage('build') {
            steps {
                script {
                    lock(resource: 'translation') {
                        dir('conversion') {
                            env.EXTRA_DINGTALK_NOTIFICATIONS = bat returnStdout: true, script: '@echo off && %WORKSPACE%/automator/automator %WORKSPACE%/automator/cfg/translation_split/send.yml --LOG_LEVEL 99'
                            // 请求任务
                            bat '@echo off && %WORKSPACE%/automator/automator %WORKSPACE%/automator/cfg/translation_split/tasks.yml --FULL_AUTOMATIC 1'
                        }
                    }
                }
            }
        }
    }

    post { 
        always { 
            script {
                build.sendCommonResult2DingTalk()
            }
        }
    }
}
