@Library("jenkins_library") _

def build = new org.devops.build()

pipeline {
    agent any
    options {
        disableConcurrentBuilds()
    }

    stages {
        stage('build') {
            steps {
                script {
                    dir("project") {
                        build.checkoutSVN(params.HG_REPOSITORY_SRC)
                        // Send Notify
                        build.sendStart2DingTalk_PubWeb()
                    }
                    build.checkoutAutomator()
                    // Environment Variables
                    env.WORKSPACE_FOLDER = "${env.WORKSPACE}/project"
                    lock(resource: "pub2web") {
                        env.PUB_VER = bat returnStdout: true, script: '@echo off && %WORKSPACE%/automator/automator %WORKSPACE%/automator/cfg/release/web/web_upgrade_pub_ver.yml --FULL_AUTOMATIC 1 --LOG_LEVEL 99'
                        print env.PUB_VER
                    }
                    bat '%WORKSPACE%/automator/automator %WORKSPACE%/automator/cfg/release/web/web_pub2tencent_cos.yml --FULL_AUTOMATIC 1'
                    lock(resource: "pub2web") {
                        bat '%WORKSPACE%/automator/automator %WORKSPACE%/automator/cfg/release/web/web_save_hg_ver_cfg.yml --FULL_AUTOMATIC 1'
                    }
                }
            }
        }
    }


    post { 
        always { 
            script {
                build.sendResult2DingTalk_PubWeb()
                if (params.MAIL_TO) {
                    build.sendResult2Emailext()
                }
            }
        }
    }
}
