@Library("jenkins_library") _

def build = new org.devops.build()

pipeline {
    agent any
    stages {
        stage('Hello') {
            steps {
                script {
                    build.ftpUploadSource()
                }
            }
        }
    }

    post { 
        failure { 
            script {
                build.sendCommonResult2DingTalk()
            }
        }
    }
}