@Library("jenkins_library") _

def build = new org.devops.build()

pipeline {
    agent any
    options {
        disableConcurrentBuilds()
    }

    stages {
        stage('build') {
            steps {
                script {
                    print build.getAtUsers()
                    build.pubToWebIntegratedCommon()
                }
            }
        }
    }

    post { 
        always { 
            script {
                build.sendResult2DingTalk_PubWeb()
                build.sendResult2Emailext()
            }
        }
    }
}
