@Library("jenkins_library") _

def build = new org.devops.build()

pipeline {
    agent any
    triggers {
        pollSCM 'H/2 * * * *'
    }
    options {
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    
    parameters {
        booleanParam description: '安静模式(不发送钉钉/邮件通知)', name: 'HG_QUIET'
    }

    stages {
        stage('generate_translation') {
            steps {
                script {
                    build.generateTranslationKV_API()
                }
            }
        }
    }
    
    post { 
        failure { 
            script {
                build.sendCommonResult2DingTalk()
            }
        }
    }
}
