@Library("jenkins_library") _

def build = new org.devops.build()

pipeline {
    agent any
    options {
        disableConcurrentBuilds()
    }

    stages {
        stage('init') {
            steps{
                script {
                    build.cleanupHGPubToolsDist()
                    build.checkoutAutomator()
                }
            }
        }
        
        stage('minigame_toggle') {
            steps {
                script {
                    lock(resource: "pub2web") {
                        bat 'node %WORKSPACE%/automator/main.js %WORKSPACE%/automator/cfg/release/mini/mini_toggle.yml --FULL_AUTOMATIC 1'
                    }
                }
            }
        }
    }


    post { 
        always { 
            script {
                build.sendResult2DingTalk_PubMinigame()
                if (params.MAIL_TO) {
                    build.sendResult2Emailext()
                }
            }
        }
    }
}
