@Library("jenkins_library") _

def build = new org.devops.build()

pipeline {
    agent any
    options {
        disableConcurrentBuilds()
    }

    stages {
        stage('init') {
            steps{
                script {
                    build.cleanupHGPubToolsDist()
                    dir("project") {
                        build.checkoutSVN(params.HG_REPOSITORY_SRC)
                    }
                    build.checkoutAutomator()
                    // Environment Variables
                    env.WORKSPACE_FOLDER = "${env.WORKSPACE}/project"

                    def parts = params.HG_MINIGAME_REPOSITORY_SRC.split("/")
                    def minigame_folder = parts[parts.size() - 1]
                    dir(minigame_folder) {
                        build.checkoutSVN(params.HG_MINIGAME_REPOSITORY_SRC)
                    }
                    // Environment Variables
                    env.MINIGAME_PROJECT = "${WORKSPACE}/${minigame_folder}"
                    // Send Notify
                    build.sendStart2DingTalk_PubMinigame()
                }
            }
        }
        
        stage('publish_static_resource') {
            steps{
                script {
                    lock(resource: "pub2web") {
                        env.PUB_VER = bat returnStdout: true, script: '@echo off && %WORKSPACE%/automator/automator %WORKSPACE%/automator/cfg/release/web/web_upgrade_pub_ver.yml --FULL_AUTOMATIC 1 --LOG_LEVEL 99'
                        print env.PUB_VER
                    }
                    bat '%WORKSPACE%/automator/automator %WORKSPACE%/automator/cfg/release/web/web_pub2tencent_cos.yml --FULL_AUTOMATIC 1'
                    lock(resource: "pub2web") {
                        bat '%WORKSPACE%/automator/automator %WORKSPACE%/automator/cfg/release/web/web_save_hg_ver_cfg.yml --FULL_AUTOMATIC 1'
                    }
                }
            }
            when { expression { params.ENABLE_PUBLISH_STATIC_RESOURCE } }
        }
        stage('minigame_upgrade_version') {
            steps {
                script {
                    lock(resource: "pub2web") {
                        bat '%WORKSPACE%/automator/automator %WORKSPACE%/automator/cfg/release/mini/mini_upgrade_pub_ver.yml --FULL_AUTOMATIC 1'
                    }
                }
            }
        }
        stage('minigame_upload') {
            steps {
                script {
                    bat '%WORKSPACE%/automator/automator %WORKSPACE%/automator/cfg/release/mini/mini_upload.yml --FULL_AUTOMATIC 1'
                }
            }
            options {
                timeout(5)
            }
        }
        stage('finish') {
            steps {
                script {
                    // 重新检出一次小程序工程，同步刚创建的提交到本次 changelog
                    def parts = params.HG_MINIGAME_REPOSITORY_SRC.split("/")
                    def minigame_folder = parts[parts.size() - 1]
                    dir(minigame_folder) {
                        build.checkoutSVN(params.HG_MINIGAME_REPOSITORY_SRC)
                    }
                }
            }
        }
    }


    post { 
        always { 
            script {
                build.sendResult2DingTalk_PubMinigame()
                build.sendResult2Emailext()
            }
        }
    }
}
