@Library("jenkins_library") _

def build = new org.devops.build()

pipeline {
    agent any
    options {
        disableConcurrentBuilds()
    }

    
    parameters {
        booleanParam description: '安静模式(不发送钉钉/邮件通知)', name: 'HG_QUIET'
    }

    stages {
        stage('build') {
            steps {
                script {
                    print build.getAtUsers()
                    build.pubToWebIntegratedCommonOld()
                }
            }
        }
    }

    post { 
        always { 
            script {
                build.sendResult2DingTalk_PubWeb()
                if (params.MAIL_TO) {
                    build.sendResult2Emailext()
                }
            }
        }
    }
}
