@Library("jenkins_library") _

def build = new org.devops.build()

pipeline {
    agent any
    parameters {
        string(
            name: 'PARAM1',
            defaultValue: 'VALUE1',
            description: '参数1'
        )
    }

    options {
        disableConcurrentBuilds()
    }

    stages {
        stage('prepare') {
            steps {
                script {
                    properties([parameters([string(defaultValue: params.PARAM1, name: 'PARAM1')])])
                }
            }
        }
        stage('build') {
            steps {
                script {
                    print "Test Build env.PARAM1=${env.PARAM1} params.PARAM1=${params.PARAM1}"
                }
            }
        }
    }
}
