@Library("jenkins_library") _

def build = new org.devops.build()

pipeline {
    agent any
    options {
        disableConcurrentBuilds()
    }

    
    parameters {
        booleanParam description: '安静模式(不发送钉钉/邮件通知)', name: 'HG_QUIET'
    }

    stages {
        stage('build') {
            steps {
                script {
                    print "Test Build 4"
                }
            }
        }
    }
    
    post { 
        failure { 
            script {
                build.sendCommonResult2DingTalk()
            }
        }
    }
}
