@Library("jenkins_library") _

def build = new org.devops.build()

pipeline {
    agent any
    triggers {
        pollSCM 'H/2 * * * *'
    }
    options {
        disableConcurrentBuilds()
    }

    stages {
        stage('generate_translation') {
            steps {
                script {
                    build.generateSendTranslationKV_API()
                }
            }
        }
    }
    
    post { 
        always { 
            script {
                build.sendCommonResult2DingTalk()
            }
        }
    }
}
